[2025-02-13T09:40:11.561+0000] {processor.py:186} INFO - Started process (PID=672) to work on /opt/airflow/dags/app.py
[2025-02-13T09:40:11.562+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:40:11.563+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:40:11.563+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:40:11.644+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:40:11.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:40:11.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:40:11.650+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.092 seconds
[2025-02-13T09:40:42.680+0000] {processor.py:186} INFO - Started process (PID=742) to work on /opt/airflow/dags/app.py
[2025-02-13T09:40:42.681+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:40:42.683+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:40:42.682+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:40:42.735+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:40:42.734+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:40:42.736+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:40:42.742+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.069 seconds
[2025-02-13T09:41:13.781+0000] {processor.py:186} INFO - Started process (PID=806) to work on /opt/airflow/dags/app.py
[2025-02-13T09:41:13.782+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:41:13.785+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:41:13.785+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:41:13.841+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:41:13.840+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:41:13.842+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:41:13.850+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.078 seconds
[2025-02-13T09:41:43.886+0000] {processor.py:186} INFO - Started process (PID=870) to work on /opt/airflow/dags/app.py
[2025-02-13T09:41:43.887+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:41:43.889+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:41:43.888+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:41:43.941+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:41:43.940+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:41:43.941+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:41:43.948+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.069 seconds
[2025-02-13T09:42:14.955+0000] {processor.py:186} INFO - Started process (PID=934) to work on /opt/airflow/dags/app.py
[2025-02-13T09:42:14.956+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:42:14.958+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:42:14.957+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:42:15.008+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:42:15.007+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:42:15.008+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:42:15.016+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.067 seconds
[2025-02-13T09:42:45.532+0000] {processor.py:186} INFO - Started process (PID=998) to work on /opt/airflow/dags/app.py
[2025-02-13T09:42:45.533+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:42:45.536+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:42:45.536+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:42:45.586+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:42:45.585+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:42:45.586+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:42:45.593+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.067 seconds
[2025-02-13T09:43:15.659+0000] {processor.py:186} INFO - Started process (PID=1061) to work on /opt/airflow/dags/app.py
[2025-02-13T09:43:15.659+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:43:15.662+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:43:15.661+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:43:15.712+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:43:15.712+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:43:15.713+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:43:15.719+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.066 seconds
[2025-02-13T09:43:45.822+0000] {processor.py:186} INFO - Started process (PID=1125) to work on /opt/airflow/dags/app.py
[2025-02-13T09:43:45.823+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:43:45.826+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:43:45.826+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:43:45.878+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:43:45.877+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:43:45.878+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:43:45.887+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.074 seconds
[2025-02-13T09:44:15.975+0000] {processor.py:186} INFO - Started process (PID=1189) to work on /opt/airflow/dags/app.py
[2025-02-13T09:44:15.975+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:44:15.977+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:44:15.977+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:44:16.025+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:44:16.024+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:44:16.025+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:44:16.035+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.063 seconds
[2025-02-13T09:44:46.132+0000] {processor.py:186} INFO - Started process (PID=1253) to work on /opt/airflow/dags/app.py
[2025-02-13T09:44:46.133+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:44:46.135+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:44:46.135+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:44:46.184+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:44:46.183+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:44:46.184+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:44:46.190+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.064 seconds
[2025-02-13T09:45:16.308+0000] {processor.py:186} INFO - Started process (PID=1317) to work on /opt/airflow/dags/app.py
[2025-02-13T09:45:16.309+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:45:16.311+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:45:16.311+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:45:16.360+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:45:16.359+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:45:16.361+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:45:16.367+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.064 seconds
[2025-02-13T09:45:47.281+0000] {processor.py:186} INFO - Started process (PID=1381) to work on /opt/airflow/dags/app.py
[2025-02-13T09:45:47.282+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:45:47.284+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:45:47.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:45:47.332+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:45:47.331+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:45:47.332+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:45:47.338+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.062 seconds
[2025-02-13T09:46:18.271+0000] {processor.py:186} INFO - Started process (PID=1445) to work on /opt/airflow/dags/app.py
[2025-02-13T09:46:18.272+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:46:18.275+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:46:18.275+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:46:18.329+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:46:18.328+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:46:18.329+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:46:18.337+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.072 seconds
[2025-02-13T09:46:49.353+0000] {processor.py:186} INFO - Started process (PID=1509) to work on /opt/airflow/dags/app.py
[2025-02-13T09:46:49.354+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:46:49.356+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:46:49.356+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:46:49.405+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:46:49.404+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:46:49.405+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:46:49.412+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.064 seconds
[2025-02-13T09:47:20.406+0000] {processor.py:186} INFO - Started process (PID=1573) to work on /opt/airflow/dags/app.py
[2025-02-13T09:47:20.406+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:47:20.408+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:20.408+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:47:20.457+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:20.456+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:47:20.457+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:47:20.465+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.064 seconds
[2025-02-13T09:47:29.590+0000] {processor.py:186} INFO - Started process (PID=1578) to work on /opt/airflow/dags/app.py
[2025-02-13T09:47:29.591+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:47:29.593+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:29.593+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:47:29.644+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:29.643+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 16, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:47:29.644+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:47:29.652+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.067 seconds
[2025-02-13T09:47:30.627+0000] {processor.py:186} INFO - Started process (PID=1579) to work on /opt/airflow/dags/app.py
[2025-02-13T09:47:30.628+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:47:30.630+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:30.629+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:47:30.680+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:30.679+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.operators.postgres_operator import PostgresOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.providers.postgres.operators.postgres.PostgresOperator` while trying to import `airflow.operators.postgres_operator.PostgresOperator`.
[2025-02-13T09:47:30.680+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:47:30.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.064 seconds
[2025-02-13T09:47:33.700+0000] {processor.py:186} INFO - Started process (PID=1580) to work on /opt/airflow/dags/app.py
[2025-02-13T09:47:33.701+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:47:33.702+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:33.702+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:47:33.743+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:47:33.742+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.operators.postgres_operator import PostgresOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.providers.postgres.operators.postgres.PostgresOperator` while trying to import `airflow.operators.postgres_operator.PostgresOperator`.
[2025-02-13T09:47:33.744+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:47:33.751+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.053 seconds
[2025-02-13T09:48:04.136+0000] {processor.py:186} INFO - Started process (PID=1644) to work on /opt/airflow/dags/app.py
[2025-02-13T09:48:04.137+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:48:04.139+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:04.139+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:48:04.193+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:04.191+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 56, in getattr_with_deprecation
    return getattr(importlib.import_module(new_module), new_class_name)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1324, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.operators.postgres_operator import PostgresOperator
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/deprecation_tools.py", line 63, in getattr_with_deprecation
    raise ImportError(error_message) from e
ImportError: Could not import `airflow.providers.postgres.operators.postgres.PostgresOperator` while trying to import `airflow.operators.postgres_operator.PostgresOperator`.
[2025-02-13T09:48:04.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:48:04.200+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.071 seconds
[2025-02-13T09:48:06.173+0000] {processor.py:186} INFO - Started process (PID=1645) to work on /opt/airflow/dags/app.py
[2025-02-13T09:48:06.173+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:48:06.175+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:06.175+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:48:06.231+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:06.228+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 16, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:48:06.233+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:48:06.247+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.079 seconds
[2025-02-13T09:48:07.492+0000] {processor.py:186} INFO - Started process (PID=1679) to work on /opt/airflow/dags/app.py
[2025-02-13T09:48:07.493+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:48:07.494+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:07.494+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:48:07.531+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:07.531+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:48:07.532+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:48:07.539+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.049 seconds
[2025-02-13T09:48:38.346+0000] {processor.py:186} INFO - Started process (PID=1740) to work on /opt/airflow/dags/app.py
[2025-02-13T09:48:38.346+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:48:38.348+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:38.348+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:48:38.392+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:48:38.389+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:48:38.396+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:48:38.403+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.060 seconds
[2025-02-13T09:49:08.576+0000] {processor.py:186} INFO - Started process (PID=1774) to work on /opt/airflow/dags/app.py
[2025-02-13T09:49:08.578+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:49:08.581+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:49:08.581+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:49:08.649+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:49:08.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:49:08.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:49:08.662+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.095 seconds
[2025-02-13T09:49:38.808+0000] {processor.py:186} INFO - Started process (PID=1837) to work on /opt/airflow/dags/app.py
[2025-02-13T09:49:38.809+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:49:38.811+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:49:38.810+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:49:38.861+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:49:38.860+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:49:38.861+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:49:38.867+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.065 seconds
[2025-02-13T09:50:09.075+0000] {processor.py:186} INFO - Started process (PID=1901) to work on /opt/airflow/dags/app.py
[2025-02-13T09:50:09.076+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:50:09.077+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:50:09.077+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:50:09.117+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:50:09.116+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:50:09.117+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:50:09.124+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.051 seconds
[2025-02-13T09:50:39.515+0000] {processor.py:186} INFO - Started process (PID=1965) to work on /opt/airflow/dags/app.py
[2025-02-13T09:50:39.516+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:50:39.518+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:50:39.518+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:50:39.570+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:50:39.569+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:50:39.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:50:39.578+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.068 seconds
[2025-02-13T09:51:10.100+0000] {processor.py:186} INFO - Started process (PID=2029) to work on /opt/airflow/dags/app.py
[2025-02-13T09:51:10.101+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:51:10.103+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:51:10.103+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:51:10.192+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:51:10.188+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:51:10.193+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:51:10.208+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.111 seconds
[2025-02-13T09:51:40.953+0000] {processor.py:186} INFO - Started process (PID=2093) to work on /opt/airflow/dags/app.py
[2025-02-13T09:51:40.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:51:40.955+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:51:40.955+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:51:41.006+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:51:41.004+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:51:41.006+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:51:41.014+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.065 seconds
[2025-02-13T09:52:11.208+0000] {processor.py:186} INFO - Started process (PID=2157) to work on /opt/airflow/dags/app.py
[2025-02-13T09:52:11.209+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:52:11.212+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:52:11.212+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:52:11.269+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:52:11.266+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:52:11.270+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:52:11.280+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.079 seconds
[2025-02-13T09:52:41.509+0000] {processor.py:186} INFO - Started process (PID=2221) to work on /opt/airflow/dags/app.py
[2025-02-13T09:52:41.510+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:52:41.512+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:52:41.512+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:52:41.581+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:52:41.579+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:52:41.581+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:52:41.589+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.085 seconds
[2025-02-13T09:53:11.748+0000] {processor.py:186} INFO - Started process (PID=2285) to work on /opt/airflow/dags/app.py
[2025-02-13T09:53:11.749+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:53:11.753+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:53:11.753+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:53:11.817+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:53:11.816+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:53:11.820+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:53:11.830+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.093 seconds
[2025-02-13T09:53:42.762+0000] {processor.py:186} INFO - Started process (PID=2349) to work on /opt/airflow/dags/app.py
[2025-02-13T09:53:42.763+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:53:42.766+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:53:42.766+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:53:42.821+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:53:42.820+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:53:42.821+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:53:42.828+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.073 seconds
[2025-02-13T09:54:12.890+0000] {processor.py:186} INFO - Started process (PID=2413) to work on /opt/airflow/dags/app.py
[2025-02-13T09:54:12.893+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:54:12.895+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:54:12.895+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:54:12.952+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:54:12.951+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:54:12.952+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:54:12.959+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.076 seconds
[2025-02-13T09:54:43.045+0000] {processor.py:186} INFO - Started process (PID=2477) to work on /opt/airflow/dags/app.py
[2025-02-13T09:54:43.047+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:54:43.049+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:54:43.049+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:54:43.114+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:54:43.112+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:54:43.115+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:54:43.123+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.086 seconds
[2025-02-13T09:55:13.164+0000] {processor.py:186} INFO - Started process (PID=2541) to work on /opt/airflow/dags/app.py
[2025-02-13T09:55:13.165+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:55:13.166+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:55:13.166+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:55:13.212+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:55:13.211+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:55:13.214+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:55:13.223+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.063 seconds
[2025-02-13T09:55:43.349+0000] {processor.py:186} INFO - Started process (PID=2605) to work on /opt/airflow/dags/app.py
[2025-02-13T09:55:43.350+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:55:43.353+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:55:43.352+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:55:43.411+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:55:43.411+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:55:43.412+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:55:43.421+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.079 seconds
[2025-02-13T09:56:13.480+0000] {processor.py:186} INFO - Started process (PID=2670) to work on /opt/airflow/dags/app.py
[2025-02-13T09:56:13.480+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:56:13.481+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:56:13.481+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:56:13.525+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:56:13.523+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:56:13.526+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:56:13.534+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.057 seconds
[2025-02-13T09:56:43.583+0000] {processor.py:186} INFO - Started process (PID=2733) to work on /opt/airflow/dags/app.py
[2025-02-13T09:56:43.584+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:56:43.586+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:56:43.586+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:56:43.650+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:56:43.648+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:56:43.650+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:56:43.660+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.083 seconds
[2025-02-13T09:57:13.793+0000] {processor.py:186} INFO - Started process (PID=2797) to work on /opt/airflow/dags/app.py
[2025-02-13T09:57:13.794+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:57:13.796+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:57:13.796+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:57:13.858+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:57:13.856+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:57:13.859+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:57:13.869+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.083 seconds
[2025-02-13T09:57:44.002+0000] {processor.py:186} INFO - Started process (PID=2861) to work on /opt/airflow/dags/app.py
[2025-02-13T09:57:44.004+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:57:44.006+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:57:44.006+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:57:44.066+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:57:44.064+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:57:44.067+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:57:44.077+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.082 seconds
[2025-02-13T09:58:14.190+0000] {processor.py:186} INFO - Started process (PID=2931) to work on /opt/airflow/dags/app.py
[2025-02-13T09:58:14.191+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:58:14.192+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:58:14.192+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:58:14.246+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:58:14.245+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:58:14.247+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:58:14.255+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.071 seconds
[2025-02-13T09:58:44.311+0000] {processor.py:186} INFO - Started process (PID=2995) to work on /opt/airflow/dags/app.py
[2025-02-13T09:58:44.312+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:58:44.313+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:58:44.313+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:58:44.373+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:58:44.371+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:58:44.374+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:58:44.382+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.076 seconds
[2025-02-13T09:59:14.624+0000] {processor.py:186} INFO - Started process (PID=3059) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:14.626+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:14.631+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:14.630+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:14.690+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:14.687+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:59:14.690+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:14.697+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.081 seconds
[2025-02-13T09:59:35.810+0000] {processor.py:186} INFO - Started process (PID=3117) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:35.810+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:35.811+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:35.811+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:35.852+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:35.851+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 15, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:59:35.852+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:35.860+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.052 seconds
[2025-02-13T09:59:37.845+0000] {processor.py:186} INFO - Started process (PID=3118) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:37.846+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:37.848+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:37.848+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:37.853+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:37.852+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 9
    headers = {
              ^
SyntaxError: '{' was never closed
[2025-02-13T09:59:37.853+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:37.866+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.027 seconds
[2025-02-13T09:59:42.894+0000] {processor.py:186} INFO - Started process (PID=3119) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:42.895+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:42.897+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:42.896+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:42.904+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:42.903+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 17
    default_args = {
                   ^
SyntaxError: '{' was never closed
[2025-02-13T09:59:42.905+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:42.920+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.032 seconds
[2025-02-13T09:59:44.957+0000] {processor.py:186} INFO - Started process (PID=3126) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:44.959+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:44.962+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:44.962+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:44.967+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:44.966+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 25
    @dag(
        ^
SyntaxError: '(' was never closed
[2025-02-13T09:59:44.967+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:44.982+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.032 seconds
[2025-02-13T09:59:49.215+0000] {processor.py:186} INFO - Started process (PID=3136) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:49.215+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:49.217+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:49.216+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:49.219+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:49.219+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 50
    book_containers = soup.find_all("div", {"class": "s-result-item"})
IndentationError: expected an indented block after 'for' statement on line 48
[2025-02-13T09:59:49.219+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:49.226+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.014 seconds
[2025-02-13T09:59:51.249+0000] {processor.py:186} INFO - Started process (PID=3137) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:51.250+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:51.252+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:51.252+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:51.256+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:51.256+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 55
    author = book.find("a", {"class": "a-size-base"})
IndentationError: expected an indented block after 'if' statement on line 54
[2025-02-13T09:59:51.256+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:51.269+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.025 seconds
[2025-02-13T09:59:52.280+0000] {processor.py:186} INFO - Started process (PID=3138) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:52.281+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:52.284+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:52.284+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:52.289+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:52.289+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1133, in get_code
  File "<frozen importlib._bootstrap_external>", line 1063, in source_to_code
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 59
    books.append({
                 ^
SyntaxError: '{' was never closed
[2025-02-13T09:59:52.290+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:52.301+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.027 seconds
[2025-02-13T09:59:58.216+0000] {processor.py:186} INFO - Started process (PID=3160) to work on /opt/airflow/dags/app.py
[2025-02-13T09:59:58.217+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T09:59:58.220+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:58.220+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T09:59:58.227+0000] {logging_mixin.py:190} INFO - [2025-02-13T09:59:58.226+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T09:59:58.228+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T09:59:58.239+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.032 seconds
[2025-02-13T10:00:00.982+0000] {processor.py:186} INFO - Started process (PID=3184) to work on /opt/airflow/dags/app.py
[2025-02-13T10:00:00.984+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:00:00.987+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:00:00.987+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:00:00.999+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:00:00.998+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:00:00.999+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:00:01.011+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.036 seconds
[2025-02-13T10:00:31.148+0000] {processor.py:186} INFO - Started process (PID=3248) to work on /opt/airflow/dags/app.py
[2025-02-13T10:00:31.148+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:00:31.149+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:00:31.149+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:00:31.151+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:00:31.151+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:00:31.151+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:00:31.158+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.012 seconds
[2025-02-13T10:01:01.559+0000] {processor.py:186} INFO - Started process (PID=3289) to work on /opt/airflow/dags/app.py
[2025-02-13T10:01:01.561+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:01:01.564+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:01:01.564+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:01:01.570+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:01:01.568+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:01:01.570+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:01:01.583+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.031 seconds
[2025-02-13T10:01:50.721+0000] {processor.py:186} INFO - Started process (PID=42) to work on /opt/airflow/dags/app.py
[2025-02-13T10:01:50.723+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:01:50.724+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:01:50.724+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:01:50.738+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:01:50.732+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:01:50.739+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:01:50.756+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.041 seconds
[2025-02-13T10:02:21.666+0000] {processor.py:186} INFO - Started process (PID=106) to work on /opt/airflow/dags/app.py
[2025-02-13T10:02:21.667+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:02:21.670+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:02:21.670+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:02:21.676+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:02:21.674+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:02:21.676+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:02:21.687+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.030 seconds
[2025-02-13T10:02:51.842+0000] {processor.py:186} INFO - Started process (PID=176) to work on /opt/airflow/dags/app.py
[2025-02-13T10:02:51.842+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:02:51.844+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:02:51.844+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:02:51.850+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:02:51.848+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:02:51.851+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:02:51.862+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.025 seconds
[2025-02-13T10:03:21.952+0000] {processor.py:186} INFO - Started process (PID=240) to work on /opt/airflow/dags/app.py
[2025-02-13T10:03:21.954+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:03:21.956+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:03:21.956+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:03:21.962+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:03:21.961+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:03:21.964+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:03:21.977+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.030 seconds
[2025-02-13T10:03:52.043+0000] {processor.py:186} INFO - Started process (PID=304) to work on /opt/airflow/dags/app.py
[2025-02-13T10:03:52.046+0000] {processor.py:914} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:03:52.047+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:03:52.047+0000] {dagbag.py:588} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:03:52.053+0000] {logging_mixin.py:190} INFO - [2025-02-13T10:03:52.049+0000] {dagbag.py:387} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/dagbag.py", line 383, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 3, in <module>
    from airflow.providers.postgres.operators.postgres import PostgresOperator
ModuleNotFoundError: No module named 'airflow.providers.postgres.operators'
[2025-02-13T10:03:52.054+0000] {processor.py:927} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:03:52.067+0000] {processor.py:208} INFO - Processing /opt/airflow/dags/app.py took 0.027 seconds
[2025-02-13T10:14:00.133+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/app.py
[2025-02-13T10:14:00.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:14:00.136+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:00.136+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:14:00.981+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:14:01.044+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.043+0000] {override.py:1769} INFO - Created Permission View: can read on DAG:fetch_and_store_amazon_books
[2025-02-13T10:14:01.054+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.054+0000] {override.py:1769} INFO - Created Permission View: can delete on DAG:fetch_and_store_amazon_books
[2025-02-13T10:14:01.061+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.061+0000] {override.py:1769} INFO - Created Permission View: can edit on DAG:fetch_and_store_amazon_books
[2025-02-13T10:14:01.062+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.061+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:14:01.069+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.068+0000] {dag.py:3058} INFO - Creating ORM DAG for fetch_and_store_amazon_books
[2025-02-13T10:14:01.080+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:01.080+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2025-02-13T10:14:01.098+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.967 seconds
[2025-02-13T10:14:31.947+0000] {processor.py:161} INFO - Started process (PID=104) to work on /opt/airflow/dags/app.py
[2025-02-13T10:14:31.949+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:14:31.951+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:31.951+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:14:32.216+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:14:32.226+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:32.226+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:14:32.233+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:14:32.233+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2024-06-20 00:00:00+00:00, run_after=2024-06-21 00:00:00+00:00
[2025-02-13T10:14:32.243+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.300 seconds
[2025-02-13T10:15:02.522+0000] {processor.py:161} INFO - Started process (PID=215) to work on /opt/airflow/dags/app.py
[2025-02-13T10:15:02.523+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:15:02.524+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:15:02.524+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:15:03.217+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:15:03.224+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:15:03.223+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:15:03.236+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.717 seconds
[2025-02-13T10:15:33.855+0000] {processor.py:161} INFO - Started process (PID=285) to work on /opt/airflow/dags/app.py
[2025-02-13T10:15:33.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:15:33.860+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:15:33.859+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:15:34.146+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:15:34.153+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:15:34.153+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:15:34.167+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.314 seconds
[2025-02-13T10:16:04.389+0000] {processor.py:161} INFO - Started process (PID=342) to work on /opt/airflow/dags/app.py
[2025-02-13T10:16:04.391+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:16:04.393+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:16:04.393+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:16:04.705+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:16:04.716+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:16:04.716+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:16:04.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.345 seconds
[2025-02-13T10:16:35.101+0000] {processor.py:161} INFO - Started process (PID=399) to work on /opt/airflow/dags/app.py
[2025-02-13T10:16:35.102+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:16:35.104+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:16:35.103+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:16:35.422+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:16:35.431+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:16:35.431+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:16:35.449+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.351 seconds
[2025-02-13T10:17:05.767+0000] {processor.py:161} INFO - Started process (PID=456) to work on /opt/airflow/dags/app.py
[2025-02-13T10:17:05.768+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:17:05.769+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:17:05.769+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:17:06.017+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:17:06.028+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:17:06.027+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:17:06.050+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.285 seconds
[2025-02-13T10:17:36.294+0000] {processor.py:161} INFO - Started process (PID=513) to work on /opt/airflow/dags/app.py
[2025-02-13T10:17:36.295+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:17:36.296+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:17:36.296+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:17:36.522+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:17:36.528+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:17:36.528+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:17:36.549+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.257 seconds
[2025-02-13T10:18:06.862+0000] {processor.py:161} INFO - Started process (PID=570) to work on /opt/airflow/dags/app.py
[2025-02-13T10:18:06.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:18:06.865+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:18:06.865+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:18:07.102+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:18:07.111+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:18:07.111+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:18:07.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.266 seconds
[2025-02-13T10:18:37.386+0000] {processor.py:161} INFO - Started process (PID=628) to work on /opt/airflow/dags/app.py
[2025-02-13T10:18:37.387+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:18:37.389+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:18:37.389+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:18:37.627+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:18:37.636+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:18:37.636+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:18:37.653+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.271 seconds
[2025-02-13T10:19:07.858+0000] {processor.py:161} INFO - Started process (PID=685) to work on /opt/airflow/dags/app.py
[2025-02-13T10:19:07.860+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:19:07.863+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:19:07.862+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:19:08.096+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:19:08.105+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:19:08.105+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:19:08.123+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.269 seconds
[2025-02-13T10:19:38.523+0000] {processor.py:161} INFO - Started process (PID=742) to work on /opt/airflow/dags/app.py
[2025-02-13T10:19:38.525+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:19:38.527+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:19:38.527+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:19:38.835+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:19:38.841+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:19:38.841+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:19:38.861+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.342 seconds
[2025-02-13T10:20:09.200+0000] {processor.py:161} INFO - Started process (PID=879) to work on /opt/airflow/dags/app.py
[2025-02-13T10:20:09.202+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:20:09.204+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:20:09.204+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:20:09.553+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:20:09.562+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:20:09.562+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:20:09.585+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.390 seconds
[2025-02-13T10:20:39.934+0000] {processor.py:161} INFO - Started process (PID=936) to work on /opt/airflow/dags/app.py
[2025-02-13T10:20:39.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:20:39.937+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:20:39.937+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:20:40.199+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:20:40.209+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:20:40.209+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:20:40.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.294 seconds
[2025-02-13T10:21:10.510+0000] {processor.py:161} INFO - Started process (PID=994) to work on /opt/airflow/dags/app.py
[2025-02-13T10:21:10.512+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:21:10.516+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:21:10.515+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:21:10.757+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:21:10.765+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:21:10.765+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:21:10.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.301 seconds
[2025-02-13T10:21:40.954+0000] {processor.py:161} INFO - Started process (PID=1051) to work on /opt/airflow/dags/app.py
[2025-02-13T10:21:40.956+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:21:40.957+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:21:40.957+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:21:41.183+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:21:41.192+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:21:41.192+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:21:41.207+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.257 seconds
[2025-02-13T10:22:11.853+0000] {processor.py:161} INFO - Started process (PID=1108) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:11.853+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:11.854+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:11.854+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:12.152+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:12.160+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:12.160+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:22:12.174+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.332 seconds
[2025-02-13T10:22:20.000+0000] {processor.py:161} INFO - Started process (PID=1148) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:20.001+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:20.003+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:20.003+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:20.198+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:20.226+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:20.226+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:22:20.239+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.243 seconds
[2025-02-13T10:22:23.129+0000] {processor.py:161} INFO - Started process (PID=1150) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:23.130+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:23.131+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:23.130+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:23.331+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:23.336+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:23.336+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:22:23.350+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.223 seconds
[2025-02-13T10:22:25.313+0000] {processor.py:161} INFO - Started process (PID=1152) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:25.315+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:25.318+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:25.318+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:25.518+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:25.516+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 20, in <module>
    'start_date': datetime(2025, 2, ),
TypeError: function missing required argument 'day' (pos 3)
[2025-02-13T10:22:25.518+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:25.524+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.226 seconds
[2025-02-13T10:22:26.396+0000] {processor.py:161} INFO - Started process (PID=1154) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:26.398+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:26.399+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:26.399+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:26.599+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:26.603+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:26.603+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:22:26.615+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.223 seconds
[2025-02-13T10:22:57.046+0000] {processor.py:161} INFO - Started process (PID=1211) to work on /opt/airflow/dags/app.py
[2025-02-13T10:22:57.049+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:22:57.056+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:57.054+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:22:57.439+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:22:57.475+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:22:57.475+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:22:57.492+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.457 seconds
[2025-02-13T10:23:40.711+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/app.py
[2025-02-13T10:23:40.713+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:23:40.717+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:23:40.717+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:23:41.512+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:23:41.654+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:23:41.654+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:23:41.690+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.986 seconds
[2025-02-13T10:24:11.794+0000] {processor.py:161} INFO - Started process (PID=109) to work on /opt/airflow/dags/app.py
[2025-02-13T10:24:11.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:24:11.796+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:24:11.796+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:24:12.032+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:24:12.040+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:24:12.040+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:24:12.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.261 seconds
[2025-02-13T10:24:42.089+0000] {processor.py:161} INFO - Started process (PID=168) to work on /opt/airflow/dags/app.py
[2025-02-13T10:24:42.089+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:24:42.090+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:24:42.090+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:24:42.308+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:24:42.315+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:24:42.315+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:24:42.388+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.302 seconds
[2025-02-13T10:25:12.517+0000] {processor.py:161} INFO - Started process (PID=242) to work on /opt/airflow/dags/app.py
[2025-02-13T10:25:12.519+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:25:12.521+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:12.521+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:25:12.834+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:25:12.844+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:12.843+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:25:12.853+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:12.853+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:25:12.860+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.346 seconds
[2025-02-13T10:25:43.277+0000] {processor.py:161} INFO - Started process (PID=299) to work on /opt/airflow/dags/app.py
[2025-02-13T10:25:43.280+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:25:43.283+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:43.283+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:25:43.609+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:25:43.619+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:43.619+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:25:43.630+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:25:43.630+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:25:43.640+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.370 seconds
[2025-02-13T10:26:14.020+0000] {processor.py:161} INFO - Started process (PID=356) to work on /opt/airflow/dags/app.py
[2025-02-13T10:26:14.021+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:26:14.023+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:14.023+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:26:14.260+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:26:14.266+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:14.266+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:26:14.273+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:14.273+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:26:14.282+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.266 seconds
[2025-02-13T10:26:44.437+0000] {processor.py:161} INFO - Started process (PID=419) to work on /opt/airflow/dags/app.py
[2025-02-13T10:26:44.439+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:26:44.442+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:44.441+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:26:44.720+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:26:44.728+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:44.727+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:26:44.735+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:26:44.735+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:26:44.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.314 seconds
[2025-02-13T10:27:14.884+0000] {processor.py:161} INFO - Started process (PID=480) to work on /opt/airflow/dags/app.py
[2025-02-13T10:27:14.885+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:27:14.886+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:14.886+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:27:15.103+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:27:15.112+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:15.112+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:27:15.120+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:15.120+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:27:15.126+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.246 seconds
[2025-02-13T10:27:45.443+0000] {processor.py:161} INFO - Started process (PID=537) to work on /opt/airflow/dags/app.py
[2025-02-13T10:27:45.446+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:27:45.449+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:45.448+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:27:45.676+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:27:45.685+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:45.685+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:27:45.692+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:27:45.692+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:27:45.701+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.263 seconds
[2025-02-13T10:28:15.917+0000] {processor.py:161} INFO - Started process (PID=594) to work on /opt/airflow/dags/app.py
[2025-02-13T10:28:15.918+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:28:15.922+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:15.922+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:28:16.165+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:28:16.171+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:16.171+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:28:16.179+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:16.179+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:28:16.187+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.277 seconds
[2025-02-13T10:28:46.473+0000] {processor.py:161} INFO - Started process (PID=651) to work on /opt/airflow/dags/app.py
[2025-02-13T10:28:46.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:28:46.479+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:46.479+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:28:46.780+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:28:46.787+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:46.787+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:28:46.795+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:28:46.795+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:28:46.804+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.344 seconds
[2025-02-13T10:29:07.990+0000] {processor.py:161} INFO - Started process (PID=702) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:07.991+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:07.992+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:07.992+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:08.215+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:08.223+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:08.223+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:29:08.231+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:08.231+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:29:08.238+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.251 seconds
[2025-02-13T10:29:11.093+0000] {processor.py:161} INFO - Started process (PID=704) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:11.095+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:11.097+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:11.096+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:11.101+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:11.100+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 66
    page += 1
    ^
SyntaxError: invalid syntax
[2025-02-13T10:29:11.101+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:11.118+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.030 seconds
[2025-02-13T10:29:13.118+0000] {processor.py:161} INFO - Started process (PID=705) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:13.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:13.121+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:13.121+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:13.125+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:13.125+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 66
    page += 1
    ^
SyntaxError: invalid syntax
[2025-02-13T10:29:13.126+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:13.141+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.027 seconds
[2025-02-13T10:29:15.173+0000] {processor.py:161} INFO - Started process (PID=712) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:15.175+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:15.177+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:15.176+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:15.181+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:15.180+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 63
    "Rating": rating.text.strip(),
    ^
IndentationError: unexpected indent
[2025-02-13T10:29:15.182+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:15.195+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.025 seconds
[2025-02-13T10:29:24.345+0000] {processor.py:161} INFO - Started process (PID=762) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:24.347+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:24.348+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:24.348+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:24.352+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:24.351+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 67
    else:
    ^
IndentationError: expected an indented block
[2025-02-13T10:29:24.352+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:24.367+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.025 seconds
[2025-02-13T10:29:27.377+0000] {processor.py:161} INFO - Started process (PID=763) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:27.378+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:27.381+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:27.381+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:27.385+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:27.384+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 101
    for book in book_data:
    ^
SyntaxError: invalid syntax
[2025-02-13T10:29:27.385+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:27.399+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.027 seconds
[2025-02-13T10:29:28.410+0000] {processor.py:161} INFO - Started process (PID=764) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:28.411+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:28.412+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:28.412+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:28.615+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:28.623+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:28.623+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:29:28.630+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:28.630+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:29:28.639+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.232 seconds
[2025-02-13T10:29:31.685+0000] {processor.py:161} INFO - Started process (PID=766) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:31.687+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:31.689+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:31.689+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:31.886+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:31.892+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:31.892+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:29:31.898+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:31.898+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:29:31.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.224 seconds
[2025-02-13T10:29:47.077+0000] {processor.py:161} INFO - Started process (PID=774) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:47.079+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:47.083+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:47.082+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:47.088+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:47.088+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 110
    if not book_data:
    ^
SyntaxError: invalid syntax
[2025-02-13T10:29:47.089+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:47.114+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.044 seconds
[2025-02-13T10:29:49.854+0000] {processor.py:161} INFO - Started process (PID=802) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:49.855+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:49.857+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:49.857+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:49.860+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:49.860+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 122
    book['Price'],
    ^
IndentationError: unexpected indent
[2025-02-13T10:29:49.860+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:49.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.031 seconds
[2025-02-13T10:29:58.508+0000] {processor.py:161} INFO - Started process (PID=825) to work on /opt/airflow/dags/app.py
[2025-02-13T10:29:58.509+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:29:58.511+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:58.511+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:29:58.514+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:29:58.514+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 131
    sql="""
    book_data = get_amazon_data_books()
    create_table >> insert_book_data_into_postgres(book_data)

# Create the DAG
dag = amazon_books_etl()
           
                                       
                                                             

                
                       ^
SyntaxError: EOF while scanning triple-quoted string literal
[2025-02-13T10:29:58.515+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:29:58.527+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.022 seconds
[2025-02-13T10:30:00.538+0000] {processor.py:161} INFO - Started process (PID=826) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:00.539+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:00.541+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:00.540+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:00.770+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:00.798+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:00.798+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:00.804+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:00.804+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:30:00.812+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.278 seconds
[2025-02-13T10:30:11.668+0000] {processor.py:161} INFO - Started process (PID=833) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:11.671+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:11.674+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:11.674+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:11.902+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:11.907+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:11.907+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:11.914+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:11.914+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:30:11.921+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.259 seconds
[2025-02-13T10:30:20.856+0000] {processor.py:161} INFO - Started process (PID=868) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:20.857+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:20.858+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:20.858+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:21.140+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:21.147+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:21.146+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:21.155+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:21.155+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:30:21.168+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.313 seconds
[2025-02-13T10:30:22.541+0000] {processor.py:161} INFO - Started process (PID=892) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:22.542+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:22.542+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:22.542+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:22.727+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:22.732+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:22.731+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:22.739+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:22.739+0000] {dag.py:3823} INFO - Setting next_dagrun for fetch_and_store_amazon_books to 2025-02-13 00:00:00+00:00, run_after=2025-02-14 00:00:00+00:00
[2025-02-13T10:30:22.746+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.206 seconds
[2025-02-13T10:30:28.706+0000] {processor.py:161} INFO - Started process (PID=894) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:28.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:28.711+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:28.710+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:28.715+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:28.714+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 39
    base_url = f"https://www.amazon.com/s?k=data+engineering+books"
    ^
IndentationError: unexpected indent
[2025-02-13T10:30:28.715+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:28.733+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.031 seconds
[2025-02-13T10:30:31.735+0000] {processor.py:161} INFO - Started process (PID=895) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:31.737+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:31.738+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:31.738+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:31.929+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:31.958+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:31.958+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:31.971+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.239 seconds
[2025-02-13T10:30:32.777+0000] {processor.py:161} INFO - Started process (PID=897) to work on /opt/airflow/dags/app.py
[2025-02-13T10:30:32.778+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:30:32.779+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:32.779+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:30:32.967+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:30:32.971+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:30:32.971+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:30:32.984+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.211 seconds
[2025-02-13T10:31:03.684+0000] {processor.py:161} INFO - Started process (PID=954) to work on /opt/airflow/dags/app.py
[2025-02-13T10:31:03.685+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:31:03.686+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:31:03.686+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:31:03.879+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:31:03.885+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:31:03.885+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:31:03.897+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.217 seconds
[2025-02-13T10:31:34.135+0000] {processor.py:161} INFO - Started process (PID=1011) to work on /opt/airflow/dags/app.py
[2025-02-13T10:31:34.137+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:31:34.139+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:31:34.139+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:31:34.350+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:31:34.357+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:31:34.356+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:31:34.368+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.237 seconds
[2025-02-13T10:32:04.892+0000] {processor.py:161} INFO - Started process (PID=1068) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:04.894+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:04.896+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:04.895+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:05.127+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:05.133+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:05.133+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:32:05.144+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.257 seconds
[2025-02-13T10:32:28.451+0000] {processor.py:161} INFO - Started process (PID=1124) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:28.452+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:28.455+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:28.455+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:28.462+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:28.461+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 99
    logger = LoggingMixin().log
    ^
IndentationError: expected an indented block
[2025-02-13T10:32:28.462+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:28.480+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.036 seconds
[2025-02-13T10:32:31.475+0000] {processor.py:161} INFO - Started process (PID=1125) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:31.476+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:31.478+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:31.477+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:31.480+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:31.479+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 123
    logger.info(f"Cleaned {len(cleaned_books)} book records")
    ^
IndentationError: unexpected unindent
[2025-02-13T10:32:31.480+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:31.489+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.016 seconds
[2025-02-13T10:32:37.517+0000] {processor.py:161} INFO - Started process (PID=1126) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:37.518+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:37.519+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:37.519+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:37.523+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:37.522+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 148
    INSERT INTO books (title, authors, price, rating)
           ^
SyntaxError: invalid syntax
[2025-02-13T10:32:37.523+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:37.536+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.022 seconds
[2025-02-13T10:32:39.559+0000] {processor.py:161} INFO - Started process (PID=1127) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:39.560+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:39.561+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:39.561+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:39.565+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:39.565+0000] {dagbag.py:348} ERROR - Failed to import: /opt/airflow/dags/app.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 344, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 839, in exec_module
  File "<frozen importlib._bootstrap_external>", line 976, in get_code
  File "<frozen importlib._bootstrap_external>", line 906, in source_to_code
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/app.py", line 165
    sql="""
                book['Title'], 
                book['Author'], 
                book['Price'], 
                book['Rating']
            ))

    # Define the flow of tasks
    raw_book_data = get_amazon_data_books()
    cleaned_book_data = clean_book_data(raw_book_data)
    create_table >> insert_book_data_into_postgres(cleaned_book_data)

# Create the DAG
dag = amazon_books_etl()
           
                               
                                
                               
                              
              

                              
                                           
                                                      
                                                                     

                
                       ^
SyntaxError: EOF while scanning triple-quoted string literal
[2025-02-13T10:32:39.566+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:39.578+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.024 seconds
[2025-02-13T10:32:45.631+0000] {processor.py:161} INFO - Started process (PID=1134) to work on /opt/airflow/dags/app.py
[2025-02-13T10:32:45.631+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:32:45.633+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:45.633+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:32:45.877+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:32:45.884+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:32:45.883+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:32:45.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.268 seconds
[2025-02-13T10:33:16.223+0000] {processor.py:161} INFO - Started process (PID=1191) to work on /opt/airflow/dags/app.py
[2025-02-13T10:33:16.225+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:33:16.228+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:33:16.228+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:33:16.453+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:33:16.460+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:33:16.460+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:33:16.472+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.254 seconds
[2025-02-13T10:33:46.842+0000] {processor.py:161} INFO - Started process (PID=1248) to work on /opt/airflow/dags/app.py
[2025-02-13T10:33:46.843+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:33:46.845+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:33:46.845+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:33:47.052+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:33:47.059+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:33:47.059+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:33:47.071+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.233 seconds
[2025-02-13T10:34:17.296+0000] {processor.py:161} INFO - Started process (PID=1305) to work on /opt/airflow/dags/app.py
[2025-02-13T10:34:17.297+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:34:17.300+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:34:17.299+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:34:17.488+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:34:17.494+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:34:17.494+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:34:17.506+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.216 seconds
[2025-02-13T10:34:47.817+0000] {processor.py:161} INFO - Started process (PID=1362) to work on /opt/airflow/dags/app.py
[2025-02-13T10:34:47.820+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/app.py for tasks to queue
[2025-02-13T10:34:47.822+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:34:47.822+0000] {dagbag.py:538} INFO - Filling up the DagBag from /opt/airflow/dags/app.py
[2025-02-13T10:34:48.110+0000] {processor.py:840} INFO - DAG(s) 'fetch_and_store_amazon_books' retrieved from /opt/airflow/dags/app.py
[2025-02-13T10:34:48.123+0000] {logging_mixin.py:188} INFO - [2025-02-13T10:34:48.123+0000] {dag.py:3036} INFO - Sync 1 DAGs
[2025-02-13T10:34:48.135+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/app.py took 0.333 seconds
